[package]
name = "ai-goal"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
log = "0.4.27"
simple_logger = "5.0.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
